# Disable specific steps
disable = ["github_cli_extensions", "pip3", "pnpm", "system"]

# Set the terminal title
set_title = true

# Display the time in step titles
display_time = false

# Cleanup temporary or old files
cleanup = true

[brew]
autoremove = true

[git]
repos = [
  "~/*",
  "~/ghq/*/*/*"
]

# Custom commands
[commands]
"Jetpack" = "vim +Jetpack +qall"
"lporg" = "lporg save -c $dotfiles/data/launchpad.yaml >/dev/null 2>&1"
"mackup" = "mackup -f backup"
"mksei" = "mksei save $dotfiles/data/keyboard_shortcuts.json"
"rtx" = "rtx plugins update --all"
