[manager]
layout = [2, 5, 3]
sort_by = "natural"
sort_sensitive = true
sort_reverse = false
show_hidden = true
linemode = "size"

[opener]
edit = [
  { run = 'vim "$@"', desc = "Vim", block = true },
  { run = 'code "$@"', desc = "VS Code" },
]
