[manager]
layout = [2, 5, 3]
sort_by = "natural"
sort_sensitive = true
sort_reverse = false
show_hidden = true

[opener]
text = [
  { exec = 'vim "$@"', desc = "Vim", block = true },
  { exec = 'code "$@"', desc = "VSCode" },
  { exec = 'open -R "$@"', desc = "Reveal in Finder" }
]
