[manager]
layout = [2, 5, 3]
sort_by = "natural"
sort_sensitive = true
sort_reverse = false
show_hidden = true

[opener]
text = [
  { exec = 'vim "$@"', display_name = "Vim", block = true },
  { exec = 'code "$@"', display_name = "VSCode" },
  { exec = 'open -R "$@"', display_name = "Reveal in Finder" }
]

