[misc]
disable = ["github_cli_extensions", "pip3", "system"]
set_title = true
display_time = false
cleanup = true

[brew]
autoremove = true

[git]
repos = [
  "~/*",
  "~/ghq/*/*/*"
]

[commands]
"gh" = "gh repo sync 5ouma/github-read-me-stats"
"Jetpack" = "vim +Jetpack +qall"
"lporg" = 'lporg save -c "$datas/launchpad.yaml" >/dev/null 2>&1'
"mackup" = "mackup -f backup"
"mksei" = 'mksei save "$datas/keyboard_shortcuts.json"'
"rtx" = "rtx plugins update && rtx upgrade"
"Shortcuts" = """
    osascript -e 'tell app "Shortcuts" to run shortcut "Backup"' \
    -e 'tell app "Shortcuts" to quit'
  """
