[misc]
disable = ["github_cli_extensions", "pip3", "system"]
set_title = true
display_time = false
cleanup = true

[brew]
autoremove = true

[git]
repos = ["~/*", "~/ghq/*/*/*"]

[commands]
"Jetpack" = "vim +Jetpack +qall"
"Shortcuts" = """
    osascript -e 'tell app "Shortcuts" to run shortcut "Backup"' \
    -e 'tell app "Shortcuts" to quit'
  """
"github-read-me-stats" = "gh status &>/dev/null && gh repo sync 5ouma/github-read-me-stats || :"
"lporg" = 'has lporg && lporg save -c="$datas/lporg.yml" || :'
"mackup" = "mackup -n backup &>/dev/null && mackup -f backup || :"
"mksei" = 'has mksei && mksei save "$datas/keyboard_shortcuts.json" || :'
"rtx" = "rtx plugins update && rtx upgrade"
