name: 🧪 Test

on:
  push:
    branches:
      - main
    paths:
      - setup
      - .github/workflows/test.yml
  pull_request:
    paths:
      - setup
      - .github/workflows/test.yml

permissions: {}

jobs:
  test:
    name: ${{ case(startsWith(matrix.os, 'macOS-'), '🍎', startsWith(matrix.os, 'Ubuntu-'), '🐧', '❓') }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu-24.04, Ubuntu-24.04-ARM, macOS-15]

    steps:
      - name: 🍺 Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@fc695c54c2032716dd4cedd007489c8e32fc8a5d # main # zizmor: ignore[stale-action-refs]

      - name: 🔨 Install tools via Homebrew
        run: |
          rm -fv /Library/Frameworks/Python.framework/Versions/3.12/bin/{2to3-3.12,idle3.12,pydoc3.12,python3.12,python3.12-config}
          brew install atuin mackup mise prek sheldon vim zoxide zsh

      - name: 🍎 Install macOS tools via Homebrew
        if: ${{ startsWith(matrix.os, 'macOS-') }}
        run: brew install batt 5ouma/tap/dorg 5ouma/tap/mksei 5ouma/tap/mli

      - name: ⚙️ Run setup
        run: zsh <(curl "https://dot.5ouma.me/${GITHUB_HEAD_REF:-HEAD}") --yes
        env:
          SETUP_SKIP_INSTALLAPPS: true
          SETUP_SKIP_RESTOREAPPSETTINGS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🐚 Launch new login shell
        run: exec zsh -ilexc exit
